#!/bin/bash
# lib/config/codex.sh — Codex Configuration Generator
# MODULE_ID: M-CONFIG-CODEX
# CONTRACT:
#   PURPOSE: Generate Codex configuration files
#   SCOPE: Project instructions, MCP config snippet, skills directory
#   DEPENDS: M-UI
#   EXPORTS:
#     generate_codex_config() — Generate Codex project instructions and MCP config

set -e

# Source dependencies
CODEX_CONFIG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CODEX_LIB_DIR="$(cd "$CODEX_CONFIG_DIR/.." && pwd)"
# shellcheck source=../ui.sh
source "$CODEX_LIB_DIR/ui.sh"

# Load profile
source "$CODEX_LIB_DIR/../profiles/codex.env"

# ═══════════════════════════════════════════════════════════════════════════
# Project Instructions
# ═══════════════════════════════════════════════════════════════════════════

generate_codex_context() {
    local conport_mode="$1"
    local entire_mode="$2"
    local os="$3"

    if [[ -f "$CONTEXT_FILE" ]]; then
        ui_info "Using existing $CONTEXT_FILE"
        return 0
    fi

    cat > "$CONTEXT_FILE" << 'CONTEXT_EOF'
# Project Instructions

This project uses **GRACE** (Guided Rapid Architecture Creation Engine) for contract-driven development.

## Project Structure

```
.
├── AGENTS.md              # Codex project instructions (this file)
├── .codex/                # Codex project-local configuration snippets
│   ├── config.toml        # MCP server snippet to merge into ~/.codex/config.toml
│   └── skills/            # Optional GRACE shortcut references
├── docs/                  # GRACE artifacts
│   ├── development-plan.xml
│   ├── requirements.xml
│   ├── knowledge-graph.xml
│   ├── verification-plan.xml
│   ├── technology.xml
│   └── decisions.xml
├── .vibestart/            # Framework files
│   └── src/
│       ├── standards/     # Development standards
│       ├── templates/     # XML templates
│       └── fragments/     # AGENTS.md components
└── (project files)
```

## GRACE Workflow

1. `$grace-init` — Bootstrap GRACE structure if `docs/` is missing
2. `$grace-plan` — Design module architecture
3. `$grace-execute` — Implement modules step-by-step
4. `$grace-verification` — Define test strategy
5. `$grace-status` — Check project health

## Standards

This project follows these development standards:

- Architecture: Layer dependencies and boundaries
- Error Handling: Logging and error management
- Git Workflow: Commit format and branching
- Agent Transparency: Action context protocol

## Quick Reference

- **Standards**: `.vibestart/src/standards/*/SKILL.md`
- **Templates**: `.vibestart/src/templates/*.xml.template`
- **GRACE Artifacts**: `docs/*.xml`
- **Marketplace Skills**: `~/.codex/skills/grace/`
CONTEXT_EOF

    if [[ "$conport_mode" != "skip" ]] || [[ "$entire_mode" == "enabled" ]]; then
        cat >> "$CONTEXT_FILE" << 'INTEGRATIONS_EOF'

## Integration Status
INTEGRATIONS_EOF

        if [[ "$conport_mode" != "skip" ]]; then
            echo "- **ConPort**: $conport_mode mode" >> "$CONTEXT_FILE"
        fi

        if [[ "$entire_mode" == "enabled" ]]; then
            echo "- **Entire.io**: enabled" >> "$CONTEXT_FILE"
        fi
    fi

    cat >> "$CONTEXT_FILE" << 'FOOTER_EOF'

---

*Generated by vibestart v3.2.0*
FOOTER_EOF

    ui_success "Created $CONTEXT_FILE"
}

# ═══════════════════════════════════════════════════════════════════════════
# MCP Configuration Snippet
# ═══════════════════════════════════════════════════════════════════════════

generate_codex_mcp() {
    local conport_mode="$1"
    local entire_mode="$2"

    mkdir -p "$(dirname "$MCP_PATH")"

    cat > "$MCP_PATH" << 'MCP_EOF'
# vibestart Codex MCP snippet
# Merge the sections below into ~/.codex/config.toml to activate project-local MCP servers.
# Codex already reads AGENTS.md from the project root automatically.

MCP_EOF

    if [[ "$conport_mode" != "full" ]] && [[ "$entire_mode" != "enabled" ]]; then
        cat >> "$MCP_PATH" << 'MCP_EMPTY_EOF'
# No MCP servers were selected for this project.
MCP_EMPTY_EOF
    fi

    if [[ "$conport_mode" == "full" ]]; then
        cat >> "$MCP_PATH" << 'CONPORT_EOF'
[mcp_servers.conport]
command = "uvx"
args = [
  "--from",
  "context-portal-mcp",
  "conport-mcp",
  "--mode",
  "stdio",
  "--workspace_id",
  "${workspaceFolder}"
]

CONPORT_EOF
        ui_info "Added ConPort Full snippet to $MCP_PATH"
    fi

    if [[ "$entire_mode" == "enabled" ]]; then
        cat >> "$MCP_PATH" << 'ENTIRE_EOF'
[mcp_servers.entire]
command = "entire-mcp"
args = []

ENTIRE_EOF
        ui_info "Added Entire.io snippet to $MCP_PATH"
    fi

    ui_success "Created $MCP_PATH"
}

# ═══════════════════════════════════════════════════════════════════════════
# Skills Directory Setup
# ═══════════════════════════════════════════════════════════════════════════

generate_codex_skills() {
    mkdir -p "$SKILLS_DIR"

    cat > "$SKILLS_DIR/README.md" << 'SKILLS_EOF'
# Codex Skills

This directory contains project-local GRACE shortcut references for Codex.

Codex marketplace skills are typically installed globally at:
`~/.codex/skills/grace/`

If you enable shortcuts during setup, vibestart will write lightweight
references here for the GRACE marketplace skills.
SKILLS_EOF

    ui_success "Created $SKILLS_DIR/"
}

# ═══════════════════════════════════════════════════════════════════════════
# Main Generator
# ═══════════════════════════════════════════════════════════════════════════

generate_codex_config() {
    local conport_mode="$1"
    local entire_mode="$2"
    local os="$3"

    source "$CODEX_LIB_DIR/../profiles/codex.env"

    ui_section "Generating Codex Configuration"

    generate_codex_context "$conport_mode" "$entire_mode" "$os"
    generate_codex_mcp "$conport_mode" "$entire_mode"
    generate_codex_skills

    ui_success "Codex configuration complete"
    return 0
}

# ═══════════════════════════════════════════════════════════════════════════
# Export Validation
# ═══════════════════════════════════════════════════════════════════════════

declare -f generate_codex_config generate_codex_context generate_codex_mcp generate_codex_skills &>/dev/null || {
    echo "[CONFIG:CODEX] Error: Export validation failed" >&2
    exit 1
}
