#!/bin/bash
# lib/config/copilot.sh — GitHub Copilot Configuration Generator
# MODULE_ID: M-CONFIG-COPILOT
# CONTRACT:
#   PURPOSE: Generate GitHub Copilot configuration files
#   SCOPE: Instructions file, skills directory (no MCP yet)
#   DEPENDS: M-UI
#   EXPORTS:
#     generate_copilot_config() — Generate Copilot instructions

set -e

# Source dependencies
COPILOT_CONFIG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COPILOT_LIB_DIR="$(cd "$COPILOT_CONFIG_DIR/.." && pwd)"
# shellcheck source=../ui.sh
source "$COPILOT_LIB_DIR/ui.sh"

# Load profile
source "$COPILOT_LIB_DIR/../profiles/copilot.env"

# ═══════════════════════════════════════════════════════════════════════════
# Instructions File Generation
# ═══════════════════════════════════════════════════════════════════════════

generate_copilot_instructions() {
    local conport_mode="$1"
    local entire_mode="$2"
    local os="$3"
    
    mkdir -p "$(dirname "$CONTEXT_FILE")"
    
    cat > "$CONTEXT_FILE" << 'INSTRUCTIONS_EOF'
# GitHub Copilot Instructions

## Project Context

This project uses **GRACE** (Guided Rapid Architecture Creation Engine) methodology.

## Project Structure

```
.
├── .github/
│   └── copilot/
│       ├── instructions.md  # This file
│       └── skills/          # Custom skills
├── docs/                    # GRACE artifacts
│   ├── development-plan.xml
│   ├── requirements.xml
│   ├── knowledge-graph.xml
│   ├── verification-plan.xml
│   ├── technology.xml
│   └── decisions.xml
└── (project files)
```

## GRACE Workflow

1. **Plan** — Define contracts in docs/development-plan.xml
2. **Execute** — Implement modules following contracts
3. **Verify** — Test against docs/verification-plan.xml
4. **Refresh** — Sync code with documentation

## Development Standards

- Follow architecture layers defined in docs/technology.xml
- Use error handling patterns from .vibestart/src/standards/
- Semantic commit messages (feat/fix/refactor/chore)
- Document all public functions with purpose, inputs, outputs

## Code Conventions

- Module contracts in MODULE_CONTRACT comments
- Semantic markup for knowledge graph navigation
- Test-driven development for critical paths

## Integration Status

INSTRUCTIONS_EOF
    
    # Add integration status
    if [[ "$conport_mode" != "skip" ]]; then
        echo "- **ConPort**: $conport_mode mode (external tool)" >> "$CONTEXT_FILE"
    fi
    
    if [[ "$entire_mode" == "enabled" ]]; then
        echo "- **Entire.io**: enabled (external tool)" >> "$CONTEXT_FILE"
    fi
    
    cat >> "$CONTEXT_FILE" << 'INSTRUCTIONS_EOF2'

## Note

GitHub Copilot does not yet support MCP servers. ConPort and Entire.io 
are external tools that can be run separately for enhanced functionality.

---

*Generated by vibestart v3.2.0*
INSTRUCTIONS_EOF2
    
    ui_success "Created $CONTEXT_FILE"
}

# ═══════════════════════════════════════════════════════════════════════════
# Skills Directory Setup
# ═══════════════════════════════════════════════════════════════════════════

generate_copilot_skills() {
    mkdir -p "$SKILLS_DIR"
    
    cat > "$SKILLS_DIR/README.md" << 'SKILLS_EOF'
# GitHub Copilot Skills

Custom skills for GitHub Copilot.

## GRACE Shortcuts

Shortcuts created during setup enable quick GRACE commands.

## Marketplace Skills

Additional skills: `~/.github/copilot/skills/grace/`
SKILLS_EOF
    
    ui_success "Created $SKILLS_DIR/"
}

# ═══════════════════════════════════════════════════════════════════════════
# Main Generator
# ═══════════════════════════════════════════════════════════════════════════

generate_copilot_config() {
    local conport_mode="$1"
    local entire_mode="$2"
    local os="$3"

    source "$COPILOT_LIB_DIR/../profiles/copilot.env"
    
    ui_section "Generating GitHub Copilot Configuration"
    
    generate_copilot_instructions "$conport_mode" "$entire_mode" "$os"
    generate_copilot_skills
    
    ui_success "GitHub Copilot configuration complete"
    return 0
}

# ═══════════════════════════════════════════════════════════════════════════
# Export Validation
# ═══════════════════════════════════════════════════════════════════════════

declare -f generate_copilot_config generate_copilot_instructions generate_copilot_skills &>/dev/null || {
    echo "[CONFIG:COPILOT] Error: Export validation failed" >&2
    exit 1
}
