#!/bin/bash
# lib/config/claude.sh — Claude Code Configuration Generator
# MODULE_ID: M-CONFIG-CLAUDE
# CONTRACT:
#   PURPOSE: Generate Claude Code configuration files
#   SCOPE: Context file, MCP servers config, skills directory
#   DEPENDS: M-UI, M-JSON
#   EXPORTS:
#     generate_claude_config() — Generate Claude context and MCP config

set -e

# Source dependencies
CLAUDE_CONFIG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_LIB_DIR="$(cd "$CLAUDE_CONFIG_DIR/.." && pwd)"
# shellcheck source=../ui.sh
source "$CLAUDE_LIB_DIR/ui.sh"
# shellcheck source=../json.sh
source "$CLAUDE_LIB_DIR/json.sh"

# Load profile
source "$CLAUDE_LIB_DIR/../profiles/claude.env"

# ═══════════════════════════════════════════════════════════════════════════
# Context File Generation
# ═══════════════════════════════════════════════════════════════════════════

generate_claude_context() {
    local conport_mode="$1"
    local entire_mode="$2"
    local os="$3"
    
    mkdir -p "$(dirname "$CONTEXT_FILE")"
    
    cat > "$CONTEXT_FILE" << 'CONTEXT_EOF'
# Project Context

This file provides context for Claude Code about the project structure and conventions.

## Project Structure

```
.
├── .claude/              # Claude Code configuration
│   ├── context.md        # This file
│   ├── mcp-servers.json  # MCP server configuration
│   └── skills/           # Custom skills
├── docs/                 # GRACE artifacts
│   ├── development-plan.xml
│   ├── requirements.xml
│   ├── knowledge-graph.xml
│   ├── verification-plan.xml
│   ├── technology.xml
│   └── decisions.xml
├── .vibestart/          # Framework files
│   └── src/
│       ├── standards/   # Development standards
│       ├── templates/   # XML templates
│       └── fragments/   # AGENTS.md components
└── (project files)
```

## GRACE Methodology

This project uses **GRACE** (Guided Rapid Architecture Creation Engine) for contract-driven development.

### Core Principles

1. **Contract-First**: Every module has a MODULE_CONTRACT before implementation
2. **Knowledge Graph**: docs/knowledge-graph.xml tracks dependencies and flows
3. **Verification**: docs/verification-plan.xml defines test strategies
4. **Semantic Markup**: Code includes structured comments for navigation

### Available Commands

Use `/grace-*` commands from GRACE marketplace:

- `/grace-init` — Bootstrap GRACE structure
- `/grace-plan` — Design module architecture
- `/grace-execute` — Implement modules step-by-step
- `/grace-verification` — Define test strategy
- `/grace-status` — Check project health

## Integration Status

CONTEXT_EOF
    
    # Add integration status
    if [[ "$conport_mode" != "skip" ]]; then
        echo "- **ConPort**: $conport_mode mode (project memory)" >> "$CONTEXT_FILE"
    fi
    
    if [[ "$entire_mode" == "enabled" ]]; then
        echo "- **Entire.io**: enabled (library documentation)" >> "$CONTEXT_FILE"
    fi
    
    cat >> "$CONTEXT_FILE" << 'CONTEXT_EOF2'

## Standards

This project follows these development standards:

- Architecture: Layer dependencies and boundaries
- Error Handling: Logging and error management
- Git Workflow: Commit format and branching
- Agent Transparency: Action context protocol

## Quick Reference

- **Standards**: .vibestart/src/standards/*/SKILL.md
- **Templates**: .vibestart/src/templates/*.xml.template
- **GRACE Artifacts**: docs/*.xml
- **Marketplace Skills**: ~/.claude/skills/grace/

---

*Generated by vibestart v3.2.0*
CONTEXT_EOF2
    
    ui_success "Created $CONTEXT_FILE"
}

# ═══════════════════════════════════════════════════════════════════════════
# MCP Servers Configuration
# ═══════════════════════════════════════════════════════════════════════════

generate_claude_mcp() {
    local conport_mode="$1"
    local entire_mode="$2"
    
    mkdir -p "$(dirname "$MCP_PATH")"
    
    # Create base MCP config
    json_create "$MCP_PATH"
    
    # Add MCP servers
    local servers='{"mcpServers": {}}'
    echo "$servers" > "$MCP_PATH"
    
    # Add ConPort if enabled
    if [[ "$conport_mode" == "full" ]]; then
        json_set "$MCP_PATH" ".mcpServers.conport" "{
  \"command\": \"$MCP_CONPORT_COMMAND\",
  \"args\": [\"$MCP_CONPORT_ARGS\"]
}"
        ui_info "Added ConPort Full to MCP servers"
    fi
    
    # Add Entire.io if enabled
    if [[ "$entire_mode" == "enabled" ]]; then
        json_set "$MCP_PATH" ".mcpServers.entire" "{
  \"command\": \"$MCP_ENTIRE_COMMAND\",
  \"args\": []
}"
        ui_info "Added Entire.io to MCP servers"
    fi
    
    ui_success "Created $MCP_PATH"
}

# ═══════════════════════════════════════════════════════════════════════════
# Skills Directory Setup
# ═══════════════════════════════════════════════════════════════════════════

generate_claude_skills() {
    mkdir -p "$SKILLS_DIR"
    
    # Create README in skills directory
    cat > "$SKILLS_DIR/README.md" << 'SKILLS_EOF'
# Claude Code Skills

This directory contains custom skills for Claude Code.

## GRACE Shortcuts

GRACE shortcuts are created here when enabled during setup.

## Custom Skills

Add your own skills by creating .md files in this directory.

## Marketplace Skills

Additional skills available from GRACE marketplace:
`~/.claude/skills/grace/`
SKILLS_EOF
    
    ui_success "Created $SKILLS_DIR/"
}

# ═══════════════════════════════════════════════════════════════════════════
# Main Generator
# ═══════════════════════════════════════════════════════════════════════════

# generate_claude_config: Generate Claude context and MCP config
# USAGE: generate_claude_config "conport_mode" "entire_mode" "os"
# RETURNS: 0 = success, 1 = failure
generate_claude_config() {
    local conport_mode="$1"
    local entire_mode="$2"
    local os="$3"

    source "$CLAUDE_LIB_DIR/../profiles/claude.env"
    
    ui_section "Generating Claude Code Configuration"
    
    # Generate context file
    generate_claude_context "$conport_mode" "$entire_mode" "$os"
    
    # Generate MCP servers config
    generate_claude_mcp "$conport_mode" "$entire_mode"
    
    # Create skills directory
    generate_claude_skills
    
    ui_success "Claude Code configuration complete"
    return 0
}

# ═══════════════════════════════════════════════════════════════════════════
# Export Validation
# ═══════════════════════════════════════════════════════════════════════════

declare -f generate_claude_config generate_claude_context generate_claude_mcp generate_claude_skills &>/dev/null || {
    echo "[CONFIG:CLAUDE] Error: Export validation failed" >&2
    exit 1
}
