#!/bin/bash
# lib/config/kilo.sh — Kilo Code Configuration Generator
# MODULE_ID: M-CONFIG-KILO
# CONTRACT:
#   PURPOSE: Generate Kilo Code configuration files
#   SCOPE: Context file, MCP settings, skills directory
#   DEPENDS: M-UI, M-JSON
#   EXPORTS:
#     generate_kilo_config() — Generate Kilo context and MCP config

set -e

# Source dependencies
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
# shellcheck source=../ui.sh
source "$LIB_DIR/ui.sh"
# shellcheck source=../json.sh
source "$LIB_DIR/json.sh"

# Load profile
source "$LIB_DIR/../profiles/kilo.env"

# ═══════════════════════════════════════════════════════════════════════════
# Context File Generation
# ═══════════════════════════════════════════════════════════════════════════

generate_kilo_context() {
    local conport_mode="$1"
    local entire_mode="$2"
    local os="$3"
    
    mkdir -p "$(dirname "$CONTEXT_FILE")"
    
    cat > "$CONTEXT_FILE" << 'CONTEXT_EOF'
# Project Context

This file provides context for Kilo Code about the project structure and conventions.

## Project Structure

```
.
├── .kilo/                 # Kilo Code configuration
│   ├── context.md         # This file
│   ├── mcp_settings.json  # MCP server configuration
│   └── skills/            # Custom skills
├── docs/                  # GRACE artifacts
│   ├── development-plan.xml
│   ├── requirements.xml
│   ├── knowledge-graph.xml
│   ├── verification-plan.xml
│   ├── technology.xml
│   └── decisions.xml
├── .vibestart/           # Framework files
│   └── src/
│       ├── standards/    # Development standards
│       ├── templates/    # XML templates
│       └── fragments/    # AGENTS.md components
└── (project files)
```

## GRACE Methodology

This project uses **GRACE** (Guided Rapid Architecture Creation Engine) for contract-driven development.

### Core Principles

1. **Contract-First**: Every module has a MODULE_CONTRACT before implementation
2. **Knowledge Graph**: docs/knowledge-graph.xml tracks dependencies and flows
3. **Verification**: docs/verification-plan.xml defines test strategies
4. **Semantic Markup**: Code includes structured comments for navigation

### Workflow

1. `$grace-init` — Bootstrap GRACE structure
2. `$grace-plan` — Design module architecture
3. `$grace-execute` — Implement modules step-by-step
4. `$grace-verification` — Define test strategy
5. `$grace-status` — Check project health

## Integration Status

CONTEXT_EOF
    
    # Add integration status
    if [[ "$conport_mode" != "skip" ]]; then
        echo "- **ConPort**: $conport_mode mode (project memory)" >> "$CONTEXT_FILE"
    fi
    
    if [[ "$entire_mode" == "enabled" ]]; then
        echo "- **Entire.io**: enabled (library documentation)" >> "$CONTEXT_FILE"
    fi
    
    cat >> "$CONTEXT_FILE" << 'CONTEXT_EOF2'

## Standards

This project follows these development standards:

- Architecture: Layer dependencies and boundaries
- Error Handling: Logging and error management
- Git Workflow: Commit format and branching
- Agent Transparency: Action context protocol

## Quick Reference

- **Standards**: .vibestart/src/standards/*/SKILL.md
- **Templates**: .vibestart/src/templates/*.xml.template
- **GRACE Artifacts**: docs/*.xml
- **Marketplace Skills**: ~/.kilocode/skills/grace/

---

*Generated by vibestart v3.1.0*
CONTEXT_EOF2
    
    ui_success "Created $CONTEXT_FILE"
}

# ═══════════════════════════════════════════════════════════════════════════
# MCP Settings Generation
# ═══════════════════════════════════════════════════════════════════════════

generate_kilo_mcp() {
    local conport_mode="$1"
    local entire_mode="$2"
    
    mkdir -p "$(dirname "$MCP_PATH")"
    
    # Create base MCP settings
    json_create "$MCP_PATH"
    
    # Add MCP servers
    local servers='{"mcpServers": {}}'
    echo "$servers" > "$MCP_PATH"
    
    # Add ConPort if enabled
    if [[ "$conport_mode" == "full" ]]; then
        json_set "$MCP_PATH" "conport" "{
  \"command\": \"$MCP_CONPORT_COMMAND\",
  \"args\": [\"$MCP_CONPORT_ARGS\"]
}"
        ui_info "Added ConPort Full to MCP settings"
    fi
    
    # Add Entire.io if enabled
    if [[ "$entire_mode" == "enabled" ]]; then
        json_set "$MCP_PATH" "entire" "{
  \"command\": \"$MCP_ENTIRE_COMMAND\",
  \"args\": []
}"
        ui_info "Added Entire.io to MCP settings"
    fi
    
    ui_success "Created $MCP_PATH"
}

# ═══════════════════════════════════════════════════════════════════════════
# Skills Directory Setup
# ═══════════════════════════════════════════════════════════════════════════

generate_kilo_skills() {
    mkdir -p "$SKILLS_DIR"
    
    # Create README in skills directory
    cat > "$SKILLS_DIR/README.md" << 'SKILLS_EOF'
# Kilo Code Skills

This directory contains custom skills for Kilo Code.

## GRACE Shortcuts

GRACE shortcuts are created here when enabled during setup.

## Custom Skills

Add your own skills by creating .md files in this directory.

## Marketplace Skills

Additional skills available from GRACE marketplace:
`~/.kilocode/skills/grace/`
SKILLS_EOF
    
    ui_success "Created $SKILLS_DIR/"
}

# ═══════════════════════════════════════════════════════════════════════════
# Main Generator
# ═══════════════════════════════════════════════════════════════════════════

# generate_kilo_config: Generate Kilo context and MCP config
# USAGE: generate_kilo_config "conport_mode" "entire_mode" "os"
# RETURNS: 0 = success, 1 = failure
generate_kilo_config() {
    local conport_mode="$1"
    local entire_mode="$2"
    local os="$3"
    
    ui_section "Generating Kilo Code Configuration"
    
    # Generate context file
    generate_kilo_context "$conport_mode" "$entire_mode" "$os"
    
    # Generate MCP settings
    generate_kilo_mcp "$conport_mode" "$entire_mode"
    
    # Create skills directory
    generate_kilo_skills
    
    ui_success "Kilo Code configuration complete"
    return 0
}

# ═══════════════════════════════════════════════════════════════════════════
# Export Validation
# ═══════════════════════════════════════════════════════════════════════════

declare -f generate_kilo_config generate_kilo_context generate_kilo_mcp generate_kilo_skills &>/dev/null || {
    echo "[CONFIG:KILO] Error: Export validation failed" >&2
    exit 1
}
