#!/bin/bash
# lib/config/qwen.sh — Qwen Configuration Generator
# MODULE_ID: M-CONFIG-QWEN
# CONTRACT:
#   PURPOSE: Generate Qwen configuration files
#   SCOPE: Context file, MCP servers config, skills directory
#   DEPENDS: M-UI, M-JSON
#   EXPORTS:
#     generate_qwen_config() — Generate Qwen context and MCP config

set -e

# Source dependencies
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
# shellcheck source=../ui.sh
source "$LIB_DIR/ui.sh"
# shellcheck source=../json.sh
source "$LIB_DIR/json.sh"

# Load profile
source "$LIB_DIR/../profiles/qwen.env"

# ═══════════════════════════════════════════════════════════════════════════
# Context File Generation
# ═══════════════════════════════════════════════════════════════════════════

generate_qwen_context() {
    local conport_mode="$1"
    local entire_mode="$2"
    local os="$3"
    
    mkdir -p "$(dirname "$CONTEXT_FILE")"
    
    cat > "$CONTEXT_FILE" << 'CONTEXT_EOF'
# Project Context

This file provides context for Qwen about the project structure and conventions.

## Project Structure

```
.
├── .qwen/                # Qwen configuration
│   ├── context.md        # This file
│   ├── mcp-servers.json  # MCP server configuration
│   └── skills/           # Custom skills
├── docs/                 # GRACE artifacts
│   ├── development-plan.xml
│   ├── requirements.xml
│   ├── knowledge-graph.xml
│   ├── verification-plan.xml
│   ├── technology.xml
│   └── decisions.xml
└── (project files)
```

## GRACE Methodology

This project uses **GRACE** for contract-driven development.

### Available Operations

- `$grace-init` — Bootstrap GRACE structure
- `$grace-plan` — Design module architecture
- `$grace-execute` — Implement modules
- `$grace-verification` — Define test strategy
- `$grace-status` — Check project health

## Integration Status

CONTEXT_EOF
    
    # Add integration status
    if [[ "$conport_mode" != "skip" ]]; then
        echo "- **ConPort**: $conport_mode mode" >> "$CONTEXT_FILE"
    fi
    
    if [[ "$entire_mode" == "enabled" ]]; then
        echo "- **Entire.io**: enabled" >> "$CONTEXT_FILE"
    fi
    
    cat >> "$CONTEXT_FILE" << 'CONTEXT_EOF2'

## Standards

- Architecture: Layer dependencies
- Error Handling: Structured logging
- Git Workflow: Semantic commits
- Agent Transparency: Action logging

---

*Generated by vibestart v3.1.0*
CONTEXT_EOF2
    
    ui_success "Created $CONTEXT_FILE"
}

# ═══════════════════════════════════════════════════════════════════════════
# MCP Servers Configuration
# ═══════════════════════════════════════════════════════════════════════════

generate_qwen_mcp() {
    local conport_mode="$1"
    local entire_mode="$2"
    
    mkdir -p "$(dirname "$MCP_PATH")"
    
    # Create MCP config
    json_create "$MCP_PATH"
    
    local servers='{"mcpServers": {}}'
    echo "$servers" > "$MCP_PATH"
    
    # Add ConPort if enabled
    if [[ "$conport_mode" == "full" ]]; then
        json_set "$MCP_PATH" "conport" "{
  \"command\": \"$MCP_CONPORT_COMMAND\",
  \"args\": [\"$MCP_CONPORT_ARGS\"]
}"
        ui_info "Added ConPort to MCP servers"
    fi
    
    ui_success "Created $MCP_PATH"
}

# ═══════════════════════════════════════════════════════════════════════════
# Skills Directory Setup
# ═══════════════════════════════════════════════════════════════════════════

generate_qwen_skills() {
    mkdir -p "$SKILLS_DIR"
    
    cat > "$SKILLS_DIR/README.md" << 'SKILLS_EOF'
# Qwen Skills

Custom skills for Qwen.

## GRACE Skills

Shortcuts created during setup.

## Marketplace

Additional skills: `~/.qwen/skills/grace/`
SKILLS_EOF
    
    ui_success "Created $SKILLS_DIR/"
}

# ═══════════════════════════════════════════════════════════════════════════
# Main Generator
# ═══════════════════════════════════════════════════════════════════════════

generate_qwen_config() {
    local conport_mode="$1"
    local entire_mode="$2"
    local os="$3"
    
    ui_section "Generating Qwen Configuration"
    
    generate_qwen_context "$conport_mode" "$entire_mode" "$os"
    generate_qwen_mcp "$conport_mode" "$entire_mode"
    generate_qwen_skills
    
    ui_success "Qwen configuration complete"
    return 0
}

# ═══════════════════════════════════════════════════════════════════════════
# Export Validation
# ═══════════════════════════════════════════════════════════════════════════

declare -f generate_qwen_config generate_qwen_context generate_qwen_mcp generate_qwen_skills &>/dev/null || {
    echo "[CONFIG:QWEN] Error: Export validation failed" >&2
    exit 1
}
